### ISSUE TITLE
Will you add download function ?

### ISSUE THREAD

**Issue by ByungjunKim** [JBGruber/LexisNexisTools#17]
Hi, I am Byungjun Kim from South Korea.
Your package is terrific work and awesome!
Is there any plan to add a download function in the package such as RSelenium?

Regards,

Byungjun Kim.

**Comment by JBGruber** [comment]
Hi, sorry for the late reply. It would be technically possible to add such a function to the package and there is an application written in Python which can apparently do that: https://github.com/AlJohri/lexis-nexis-uni-downloader

But there are two problems that keep me from doing that (3 if you take into consideration that I have very little time to work on this at the moment): 1. What are the legal implications? As far as I'm aware it is against the ToS of LexisNexis to download files using a scraper 2. How are users authenticated? This was my problem with the python tool as my university account apparently had a different way of authentication than what the above package uses. If there are several different authentication paths, it could be quite difficult to support them all.

I'm not saying I will never do it or I wouldn't consider a PR. But there are currently no plans to go ahead with this.

**Comment by ByungjunKim** [comment]
Thank you for reply.
