### ISSUE TITLE
Converting dates error

### ISSUE THREAD

**Issue by JKerms89** [JBGruber/LexisNexisTools#18]
Dear JBGruber,

I have downloaded articles from the same newspaper, but I receive the following warning message:

> LNToutput <- lnt_read(my_files)
Creating LNToutput from 1 file...
	...files loaded [0.50 secs]
	...articles split [0.63 secs]
	...lengths extracted [0.68 secs]
	...headlines extracted [0.71 secs]
	...newspapers extracted [0.74 secs]
	...dates extracted [0.81 secs]
	...authors extracted [0.83 secs]
	...sections extracted [0.85 secs]
	...editions extracted [0.85 secs]
More than one language was detected. Choose one: 

1: Don't convert dates
2: Italian (96.86%)
3: Spanish (11.95%)
4: Portuguese (11.95%)

# I select option 1, as the newspaper is an Italian one. 

Selection: 1
	...dates converted [4.68 secs]
	...metadata extracted [4.70 secs]
	...article texts extracted [4.70 secs]
	...superfluous whitespace removed [4.76 secs]
Elapsed time: 4.76 secs

docs <- lnt_convert(LNToutput, to = "rDNA")

Warning message:
**In lnt2rDNA(x, what = what, collapse = collapse) :
  One or more (or all) dates could not be converted to POSIXct. NA entries in 'date' were filled with the system's time and date instead.**

Unfortunately, I lose all the data regarding the time of the article when on the rDNA dataframe. Can you kindly help me?

Many thanks,

Jan

**Comment by JBGruber** [comment]
Unfortunately, this is not reproducible for me. As the warning says, when there are `NA`s in the time column, the system's time and date are used instead. This does not work for you? What exactly do you mean with "lose all the data regarding the time"? 

Can maybe share what the `data.frame` you are trying to import in `rDNA` looks like? below is a short example how you could do this so it would be helpful to track down your problem.

``` r
library(LexisNexisTools)
LNToutput <- lnt_read(lnt_sample(copy = FALSE))
#> Creating LNToutput from 1 file...
#>  ...files loaded [0.0036 secs]
#>  ...articles split [0.012 secs]
#>  ...lengths extracted [0.013 secs]
#>  ...newspapers extracted [0.013 secs]
#>  ...dates extracted [0.016 secs]
#>  ...authors extracted [0.016 secs]
#>  ...sections extracted [0.017 secs]
#>  ...editions extracted [0.018 secs]
#>  ...headlines extracted [0.019 secs]
#>  ...dates converted [0.026 secs]
#>  ...metadata extracted [0.032 secs]
#>  ...article texts extracted [0.036 secs]
#>  ...paragraphs extracted [0.056 secs]
#>  ...superfluous whitespace removed [0.072 secs]
#> Elapsed time: 0.072 secs

df <- lnt_convert(LNToutput, to = "rDNA")
dplyr::glimpse(df)
#> Rows: 10
#> Columns: 10
#> $ id      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
#> $ title   <chr> "Lorem ipsum dolor sit amet", "Lorem ipsum dolor sit amet", "…
#> $ text    <chr> "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eti…
#> $ coder   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
#> $ author  <chr> "Andrew Sparrow", "Simon Tisdall", "TREVOR Kavanagh", "Tom Co…
#> $ source  <chr> "Guardian.com", "Guardian", "The Sun (England)", "The Times (…
#> $ section <chr> "", "", "FEATURES; Pg. 6", "NEWS; Pg. 3", "EDITORIAL; Pg. 24"…
#> $ notes   <chr> "ID: 1", "ID: 2", "ID: 3", "ID: 4", "ID: 5", "ID: 6", "ID: 7"…
#> $ type    <chr> "newspaper", "newspaper", "newspaper", "newspaper", "newspape…
#> $ date    <dttm> 2010-01-11 01:00:00, 2010-01-11 01:00:00, 2010-01-11 01:00:0…
```

<sup>Created on 2021-02-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
