### ISSUE TITLE
Dates are not being properly read

### ISSUE THREAD

**Issue by ericoffn** [JBGruber/LexisNexisTools#19]
Hi,

I’m facing a problem with the date formats. Apparently, lnt_read sometimes mixes up part of the title with the date published. For example, I have an article with the title:

**Rebuilding better after Covid-19, part 1**

When I read it without converting the dates, I see that the code reads “19, part 1” as the date.

My solution is to manually change the title: For example, Covid.19, first part. (deleting or replacing the , doesn’t work).

But this is obviously problematic for a big amount of articles, so I was wondering what can be done in the code to get rid of this problem?

Thanks!

**Comment by JBGruber** [comment]
That's hard to troubleshoot without actual data. I would suggest you

1. `LexisNexisTools::lnt_read()` without converting dates
2. find some way to separate the title out
3. then run `LexisNexisTools::lnt_asDate()` after the fact

**Comment by JBGruber** [comment]
Any news on this? Otherwise I will close the issue this week.
