### ISSUE TITLE
"Load Date:" and "Graphic:" are not filtering out 

### ISSUE THREAD

**Issue by julcope** [JBGruber/LexisNexisTools#22]
Greetings - thank you so much for creating this package - it has saved me so much time. 

I am having one issue with using this function: lnt_read(). The issue is that the "exclude_lines" argument does not seem to be filtering out "Load Date:" and "Graphic:" from my articles. I am able to remove "Load-date" by adding 'end_keyword = "^Load-Date:",' but I would like to also remove the graphic tag where applicable. 

This is the code that appears int he help box for exclude lines: 
exclude_lines = "^LOAD-DATE: |^UPDATE: |^GRAFIK: |^GRAPHIC: |^DATELINE: ",
  
For example this is the end of one of the articles I have after running it through lnt_read() with the above exclude_lines argument passed in:

"Graphic    photo photos by author/ USA TODAY Load-Date: September 19, 2018"

----
If you have any advice, I'd appreciate it - thank you!

**Comment by barakZur** [comment]
Hi Julcope,

Did find a solution to your inquiry? will be happy to hear. 

Thanks,
Barak

**Comment by JBGruber** [comment]
Hi @julcope,

sorry for the late reply. `exclude_lines` is case-sensitive by design, as it would otherwise often filter out legitimate text. So you could use:

```
LNToutput <- lnt_read(file, exclude_lines = "^Graphic |^Load-Date:")
```

to get rid of these lines. `^` means start of the line, btw, and `|` means or.

**Comment by barakZur** [comment]
hi @JBGruber 

As a follow up to this question, I have tried to amend the command in the following way:

````
LNToutput <- lnt_read(filelist,
                      encoding = "UTF-8",
                      extract_paragraphs = FALSE,
                      convert_date = `TRUE,`
                      start_keyword = "auto",
                      end_keyword = "^Classification",
                      length_keyword = "auto",
                      author_keyword = "auto",
                      exclude_lines = "^Language: |^Subject: |^Industry: |^Geographic: |^Load-Date:",
                      recursive = FALSE,
                      file_type = c("txt", "rtf", "doc", "pdf", "docx", "zip"),
                      remove_cover = TRUE,
                     verbose = TRUE
)
````

As you've commented, I used case-sensitive words to get rid of all useless infos at the end of my newspapers. Yet, I am getting the following error:

Error in lnt_read(filelist, encoding = "UTF-8", extract_paragraphs = FALSE,  : 
  could not find function "lnt_read"

I attach here a sample of the documents I've been using: 

[_ AMP Capital a toshin adviser.docx](https://github.com/JBGruber/LexisNexisTools/files/8778253/_.AMP.Capital.a.toshin.adviser.docx)
[_ Boy, 13, killed by bus.docx](https://github.com/JBGruber/LexisNexisTools/files/8778254/_.Boy.13.killed.by.bus.docx)
[_ MOVIES.docx](https://github.com/JBGruber/LexisNexisTools/files/8778255/_.MOVIES.docx)
[_ RUGBY UNION - Ireland keep hopes alive.docx](https://github.com/JBGruber/LexisNexisTools/files/8778256/_.RUGBY.UNION.-.Ireland.keep.hopes.alive.docx)
