### ISSUE TITLE
Problems parsing dates from NexisUni

### ISSUE THREAD

**Issue by M-Gartiser** [JBGruber/LexisNexisTools#23]
At first I want to thank you very much for this great package, Johannes. It saved me a lot of time and effort when handling NexisUni documents. 

I just wanted to make you aware of an issue I had in parsing dates for German newspaper articles. I had the curious situation where lnt_read() extracted certain parts of the headline or subtitles fitting to the pre-defined regex-patterns when searching for the articles date. 

To give a short example with the extracted parts highlighted:

Allianz erwartet erneut 10 Prozent Gewinnplus; Beitraege sollen in **2000 um 4**,5 Prozent klettern - 99er-Dividende steigt auf 1,25 (1,12) Euro je Aktie

I managed to find a very basic solution fitting my particular purposes by adjusting the pattern used to identify the date within lnt_parse_uni():

```
date.v <- vapply(df.l, FUN.VALUE = character(1), function(i) {
    . <- stringi::stri_extract_last_regex(
      str = i$meta[seq_len(10)],
      pattern = "^\\w+ \\d+, \\d+|^\\d+ \\w+ \\d+|^\\d+. \\w+ \\d+|^\\w+ \\d+. \\w+ \\d+"
    )
    na.omit(.)[1]
  })
```

Even though it might not be applicable for general purposes I thought it might be worth following up on. 

Thanks again!

**Comment by JBGruber** [comment]
It looks like this does not break anything in my tests, so I changed the line. Thank you!
