### ISSUE TITLE
Getting rid of the classification part 

### ISSUE THREAD

**Issue by barakZur** [JBGruber/LexisNexisTools#24]
Hallo LexisNexisTools community, 

I have a bunch of newspaper articles that were downloaded from LexisNexis. I want to get rid of all the content that bellow the classification part (Language/ Publication-type/ Journal code/subject/industry/etc...). I know I can re-download those articles without the classification part, but we are talking about a hefty amount of documents, so it will not be a useful advise atm... I was wondering whether there is an easy way to get rid of this part by coding. I tried to modify the `lnt_read` command in the following way, but it does not seem to work:

```
LNToutput <- lnt_read(filelist,
                      encoding = "UTF-8",
                      extract_paragraphs = FALSE,
                      convert_date = TRUE,
                      start_keyword = "auto",
                      end_keyword = "^Classification:",
                      length_keyword = "auto",
                      author_keyword = "auto",
                      exclude_lines = "^LOAD-DATE: |^UPDATE: |^GRAFIK: |^GRAPHIC: |^DATELINE:",
                      recursive = FALSE,
                      file_type = c("txt", "rtf", "doc", "pdf", "docx", "zip"),
                      remove_cover = TRUE,
                      verbose = TRUE
)
```

Appreciate the help.

Barak

**Comment by JBGruber** [comment]
Hi @barakZur,

this looks correct to me and I would have expected it to work. Could you provide an example file, so I can have a closer look?

**Comment by barakZur** [comment]
Dear Johannes, 

Thank you for the quick reply. 

Sure- I attach a random newspaper article. When I run the code I mention above, I receive the following error: 

> Creating LNToutput from 1 file...
	...files loaded [0.0041 secs]
Error in lnt_parse_uni(lines = lines$uni, extract_paragraphs = extract_paragraphs,  : 
  No articles found to parse.

[_ Boy, 13, killed by bus.docx](https://github.com/JBGruber/LexisNexisTools/files/8772604/_.Boy.13.killed.by.bus.docx)

Best,
Barak

**Comment by JBGruber** [comment]
Hi @barakZur ,

Your file does not contain the patter `"^Classification:"`. You need to use `end_keyword = "^Classification"` instead. Then it works fine for me.

**Comment by barakZur** [comment]
Hi @JBGruber,

Thank you, it worked! But it also opened new problems. Now the meta-data are mixed-up. 

 When I use to following code:

`LNToutput <- lnt_read(filelist,
                      encoding = "UTF-8",
                      extract_paragraphs = FALSE,
                      convert_date = TRUE,
                      start_keyword = "^Body",
                      end_keyword = "^Classification",
                      length_keyword = "auto",
                      author_keyword = "auto",
                      exclude_lines = "^LOAD-DATE: |^UPDATE: |^GRAFIK: |^GRAPHIC: |^DATELINE:",
                      recursive = FALSE,
                      file_type = c("txt", "rtf", "doc", "pdf", "docx", "zip"),
                      remove_cover = TRUE,
                      verbose = TRUE
)

meta_articles_df<- lnt_convert(LNToutput, to = "data.frame")

meta_articles_df
data(meta_articles_df)
View(meta_articles_df)
`

What I see that from the second item onwards, they newspaper and the headline columns are not showing the correct info. 

That's what I get with the above-mentioned code and the attached documents: 

![image](https://user-images.githubusercontent.com/106242519/170460001-0fa6c303-6fa4-4f94-a798-40f1dc5108c7.png)
[_ AMP Capital a toshin adviser.docx](https://github.com/JBGruber/LexisNexisTools/files/8777913/_.AMP.Capital.a.toshin.adviser.docx)
[_ Boy, 13, killed by bus.docx](https://github.com/JBGruber/LexisNexisTools/files/8777915/_.Boy.13.killed.by.bus.docx)
[_ MOVIES.docx](https://github.com/JBGruber/LexisNexisTools/files/8777916/_.MOVIES.docx)
[_ RUGBY UNION - Ireland keep hopes alive.docx](https://github.com/JBGruber/LexisNexisTools/files/8777917/_.RUGBY.UNION.-.Ireland.keep.hopes.alive.docx)

**Comment by schelp-cpu** [comment]
Hi,
I just wanted to a) thank you for your efforts, and the great package, and b) report that I encounter the same issue. I want to exclude the classification stuff since it really messes with keyword analysis, but if I specify the end keyword as end_keyword = "^Language, the metadata is messed up (including lots of missing dates). It does remove the things out of the article column, though. Attaching a sample file from freshly a downloaded document.  
Many thanks!! 
[Cold_War_2.0_Jan 01, 2016-Dec 31, 2021_199801831.docx](https://github.com/JBGruber/LexisNexisTools/files/11880626/Cold_War_2.0_Jan.01.2016-Dec.31.2021_199801831.docx)

**Comment by JBGruber** [comment]
I had a closer look today and added and argument `remove_classification`, which is `TRUE` by default and removes the classification part more consistently. It passes the tests and seems to work well with you files.
