### ISSUE TITLE
lnt_read directory of zip files

### ISSUE THREAD

**Issue by violawiegand** [JBGruber/LexisNexisTools#25]
Hello,
your package is so useful for processing Nexis data!
Previously, I have used `lnt_read` directly with docx files. Now I have been given a lot of zip files so that I would like to read in the zip files instead. When just working with one zip file, this works fine.
For example, the following code works (where "search_term" is the name of the folder – I want to run this over several folders with different search terms and years)

`nexis_articles <- lnt_read(paste0("./docx/", search_term, "/1992W1to500.ZIP"), end_keyword = "End of Document", remove_cover = FALSE, verbose = TRUE, convert_date = FALSE, file_type = "zip", recursive = TRUE) `

Because each of my folders contains many zip files, I would like to read in the whole folder rather than specifically name each file. Unfortunately, I run into an error when I change to just the folder:

`nexis_articles <- lnt_read(paste0("./docx/", search_term), end_keyword = "End of Document", remove_cover = FALSE, verbose = TRUE, convert_date = FALSE, file_type = "zip", recursive = TRUE)`

the error message reads: "Error in unzip(files[zips], exdir = temp) : invalid zip name argument" – any idea why?

[By contrast, the same code did work with docx files in the directory
`nexis_articles <- lnt_read(paste0("./docx/", search_term), end_keyword = "End of Document", remove_cover = FALSE, verbose = TRUE, convert_date = FALSE, file_type = "docx", recursive = TRUE)`]

**Comment by JBGruber** [comment]
Thank you for reporting this issue. It turns out that the `unzip()` function, which I use under the hood here, can only deal with one zip file at a time. I fixed this now and it should work for you with the development version.
