### ISSUE TITLE
Extracting dates from articles with corrections appended

### ISSUE THREAD

**Issue by duncanhobbs** [JBGruber/LexisNexisTools#26]
Thank you for this wonderful package.

I am having trouble parsing some dates correctly when reading in articles using lnt_read()

```
my_files = list.files(pattern = ".docx", path = getwd(),
                       full.names = TRUE, recursive = TRUE, ignore.case = TRUE, convert_date = FALSE)

dat = lnt_read(my_files)
```

For some of the files,  I see they have a "correction appended" flag and so I think the date is not being extracted correctly since it is not in the usual place. 

I attached an example of one of the documents below.

[Sample Article with Correction Appended.docx](https://github.com/JBGruber/LexisNexisTools/files/10608801/Sample.Article.with.Correction.Appended.docx)

 Is there a way to extract the "correction date" at the very end of the article?

**Comment by JBGruber** [comment]
Hi, sorry, but this is such a rare case, it's out of scope for the package. Here is a workaround:

```r
curl::curl_download("https://github.com/JBGruber/LexisNexisTools/files/10608801/Sample.Article.with.Correction.Appended.docx", 
                    "test_file.docx")

# parse file without removing cover page or parsing dates
out <- lnt_read("test_file.docx", 
                convert_date = FALSE,
                remove_cover = FALSE)

library(tidyverse)
out@meta <- out@meta |> 
  mutate(Date = stringr::str_extract(
    out@articles$Article,
    "(?<=Correction-Date: )\\w+ \\d{1,2}, \\d{4}" # extract dates in this format
  )) |> 
  mutate(Date = LexisNexisTools:::lnt_asDate(Date)) # use the unexported date parser for convenience

out@meta$Date
```
