### ISSUE TITLE
Compatibility with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [JBGruber/LexisNexisTools#30]
This package no longer passes its checks with the current tibble release candidate, perhaps triggered by https://github.com/tidyverse/tibble/pull/1574 (now keeping attributes named `"x"` and `"n"`  after `new_tibble()` and `as_tibble()`). Please see https://github.com/tidyverse/tibble/blob/main/revdep/problems.md#lexisnexistools for details.

Should we be doing things differently? Can you please take a look and, if appropriate, submit an update to CRAN? Thanks!

**Comment by JBGruber** [comment]
Thanks for letting me know. The issue seems to be that the current version of tibble has an attribute called `.internal.selfref`, that you are not carrying forward. Not sure what this attribute was for, but it has no relevance for me. I'll change the tests and submit a new version to CRAN.

**Comment by JBGruber** [comment]
It's arguably a bit silly to test against specific objects. The specific class I use here is a just a bit annoying to test otherwise. Let me know if you think it's weird that `.internal.selfref` was there in the first place @krlmlr. Otherwise I'll submit this to CRAN tomorrow evening.

**Comment by krlmlr** [comment]
Ah, this is probably tidyverse/tibble#1557. CC @TimTaylor.

Before, we were doing things inconsistently for data.table -> tibble conversion. The current behavior is correct. Thanks for the very quick action!
