### ISSUE TITLE
lnt_sample() violates CRAN policies by writing a file to current working directory

### ISSUE THREAD

**Issue by kbenoit** [JBGruber/LexisNexisTools#4]
I noticed that `lnt_sample()` writes to the user's current directory.

From https://cran.r-project.org/web/packages/policies.html:

> - Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). 

Suggest putting this in `inst/extdata` instead. See http://r-pkgs.had.co.nz/data.html.

**Comment by JBGruber** [comment]
The only thing `lnt_sample()` actually does is to grab the `sample.TXT` from `inst/extdata` and copies it to the user's working directory. This does not happen during installation but only when the function is called.

I think the reason why a `sample.TXT` ended up in the package directory was that in one of the test scripts the sample file was created but I forgot to put `teardown()` at the end to clean up. It should be fixed now, but please let me know if you still think there is a problem.

**Comment by kbenoit** [comment]
Since it's a read-only operation, why not just call it directly in your examples, as
```r
system.file("extdata", "sample.TXT", package = "LexisNexisTools")
```

**Comment by JBGruber** [comment]
Good point. All but one of the tests only read the file and make no changes. Thanks!
