### ISSUE TITLE
Error in lnt_asDate(date.v, ...) : No valid dates found.

### ISSUE THREAD

**Issue by ying-ying-chen** [JBGruber/LexisNexisTools#6]
Hi, I am using lnt_read to convert LexisNexis text file but get an error "Error in lnt_asDate(date.v, ...) : No valid dates found."

I notice that my text file is not quite structured the same as your in the lnt_sample(). Could that be the issue?

Thank you so much!

Here is how my text looks like:

USA TODAY

November 9, 2015 Monday

 FIRST EDITION

Obama makes the wrong call on Keystone XL pipeline

SECTION: 

NEWS; Pg. 7A

LENGTH: 452 words

By the time President Obama finally rejected the proposed Keystone XL pipeline Friday after an absurdly prolonged seven-year review, the project to bring oil from Canadian tar sands to U.S. Gulf Coast refineries had become a wildly exaggerated symbol for both sides in an increasingly nasty fight.

As Obama himself noted, Keystone "would neither be a silver bullet for the economy ... nor the express lane to climate disaster proclaimed by others."

In fact, Keystone was mostly just another energy pipeline in a nation that's already crisscrossed by more than 150,000 miles of them, one that took on disproportionate importance as the debate dragged on.

On balance, the 1,179-mile Keystone line warranted approval. It would have given the U.S. a substantial new supply of oil from a trusted neighbor. Like it or not, the USA still imports about a quarter of its oil, much of it from volatile nations that are hardly close allies like Canada.

Environmentalists' concern for the planet is valid, but so is concern for how to fuel the quarter billion vehicles already on U.S. roads and highways. Sources such as solar and wind are probably decades away from displacing petroleum. Most of the 800,000 barrels a day that would have traveled through Keystone XL would have stayed in the U.S., a valuable hedge against future supply constraints.

The State Department had determined that Keystone wouldn't significantly affect carbon emission levels. Most or all of that Canadian oil will likely be produced anyway, perhaps to go to consumers in China or elsewhere via alternative pipelines, and some to the U.S. via rail tanker cars, a far more dangerous method of transport than pipelines, as various train disasters have shown.

Environmentalists' campaign to keep tar sands oil in the ground is unlikely to succeed. Current low world oil prices are making it less inviting to move the oil now, but if history is any guide, oil prices will rebound as they always have.

Supporters' argument that the pipeline, estimated to cost at least $8 billion, would have been an economically vital source of jobs was overblown. Studies showed it would have produced roughly 42,000 jobs during the two years or so it took to build -- nothing to sneeze at, but a tiny fraction of the nation's 143 million jobs. Once construction was over, estimates were that permanent employment would drop to about 35 jobs.

Obama said approving Keystone would have undercut U.S. leadership ahead of this month's climate change talks in Paris. Actually, putting a price on carbon pollution, a step thwarted by the Republican-controlled Congress, would be a far better way to demonstrate American leadership than the symbolic move of killing a pipeline project. 

GRAPHIC: photo AFP/Getty Images

LANGUAGE: ENGLISH

PUBLICATION-TYPE: NEWSPAPER

SUBJECT: 

OIL SANDS (90%); PRICES (89%); OIL & GAS PRICES (89%); EDITORIALS & OPINIONS (79%); EMISSIONS (78%); US PRESIDENTS (78%); ENVIRONMENTAL ACCIDENTS & DISASTERS (78%); SUPPLY CHAIN DISRUPTIONS (78%); OIL & GAS INDUSTRY (78%); PETROLEUM PRODUCTS (78%); PIPELINE TRANSPORTATION (78%); OIL & GAS PIPELINE CONSTRUCTION (78%); US REPUBLICAN PARTY (77%); RAIL TRANSPORTATION ACCIDENTS (76%); CONSUMERS (76%); CLIMATE CHANGE (76%); CLIMATOLOGY (76%); ENVIRONMENT & NATURAL RESOURCES (76%); SEVERE WEATHER (76%); WIND ENERGY (75%); ENVIRONMENTALISM (75%); IMPORT TRADE (74%); POLLUTION & ENVIRONMENTAL IMPACTS (72%); CRUDE OIL MARKETS (70%); TRAINS (70%); SHORTAGES (68%); AIR POLLUTION (64%); EMPLOYMENT (64%); BULK SHIPPING (58%)

EDITORIAL

PERSON: 

BARACK OBAMA (90%)

COUNTRY: 

UNITED STATES (94%); CANADA (93%); NORTH AMERICA (93%); CHINA (79%); FRANCE (72%)

LOAD-DATE: November 9, 2015

Copyright 2015 Gannett Company, Inc.All Rights Reserved

**Comment by JBGruber** [comment]
Hi @lululy, thanks for letting me know. I couldn't see what the problem was from your question so I downloaded the article myself and found that unlike ALL articles from LexisNexis I've seen before, it uses a different line to count the articles:

> 1 of 1 DOCUMENT

(Usually it's "DOCUMENTS"). So the solution to your problem is fortunately very easy. Just use the following to read in your file:

```
LNToutput <- lnt_read("yourfile.TXT", start_keyword = "\\d+ of \\d+ DOCUMENT$")
```

Please let me know if this works. I will then include this format in the "auto" option for this argument in the next version.

**Comment by ying-ying-chen** [comment]
Hi @JBGruber Thank you so much for replying! 
I still get the error messages: 
`Error in lnt_asDate(date.v, ...) : No valid dates found`
`3.stop("No valid dates found.")`
`2. | lnt_asDate(date.v, ...)`
`1.lnt_read(getwd(), start_keyword = "\\d+ of \\d+ DOCUMENT$")`

Here is my codes:
`setwd("xxx/test")`
`LNToutput <- lnt_read(getwd(), start_keyword = "\\d+ of \\d+ DOCUMENT$")`

Here is the text file(as below) in my working directory.
[ev1Corpus.txt](https://github.com/JBGruber/LexisNexisTools/files/2975344/ev1Corpus.txt)

Thank you again!

**Comment by JBGruber** [comment]
That's strange. Your file looks nothing like it should. Working around that is a bit difficult. How did you download it?

I made a small wiki which shows how to download files, so they work best with the package. Could you have a look [here](https://github.com/JBGruber/LexisNexisTools/wiki/Downloading-TXT-Files-From-Nexis) and let me know if this is how you downloaded the file?

**Comment by ying-ying-chen** [comment]
Hi  @JBGruber Thank you again and sorry for the late reply! That is not the way we get the data unfortunately. We got it from Nexis Lexis Text Assembler from our library's access. Perhaps that is why our data have different structure. 
So I guess, to use the package, we need to download the data using the way shown in the link?
Thank you again!

**Comment by JBGruber** [comment]
Ok, I have never heard of Nexis Lexis Text Assembler. If this is really all you can get, I can think of dealing with it in two ways. 

The first is to set the terms used to split the articles explicitly. See this image I created to make it clear what they mean:

<p align="center">
<a href="https://ibb.co/fj5YjG"><img src="https://preview.ibb.co/fOfNdb/LN.png" alt="LN" border="1"></a>
</p>

In your file `end_keyword` and `length_keyword` are actually similar to the usual output. But the `start_keyword` (beginning in the image) is completely missing. After inspecting your file, it seems though that "LOAD-DATE:" is at the end of each article, which means we can use this instead:

```
lnt <- lnt_read("ev1Corpus.txt", 
                start_keyword = "LOAD-DATE:", 
                end_keyword = "^LANGUAGE:",
                length_keyword = "^LENGTH:", 
                convert_date = TRUE)
```
This works, but has problems identifying the headline, author newspaper and so on. Articles and dates are identified correctly though. The approach misses the first article, but you can easily get around that by adding "LOAD-DATE:" before your first article. You might be able to use a different keyword, but I don't see any obvious candidates.

The second approach needs a lot more manual fiddling, but I think you could retain most of the meta-data. Use a capable text editor (like notepad++, atom, kate or you can just use RStudio) to open your corpus file and add a start_keyword before every article. For example "1 of 1 DOCUMENTS" (you don't need to properly number the articles). Then the package will be able to recognise where an article begins. If you don't have a lot of articles and the meta data is important to you, this might be a preferable option. But check if this works as intended first with a few articles.

**Comment by JBGruber** [comment]
Hi @lululy. Were you able to resolve your problem? Can this be closed?
